name: multi-object
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.0.130
  - ffmpeg=4.1.3
  - future=0.17.1
  - h5py=2.10.0
  - matplotlib=3.1.1
  - moviepy=0.2.3.5
  - numpy=1.16.5
  - opencv=4.1.1
  - pillow=6.1.0
  - pymongo=3.8.0
  - python=3.7.4
  - pytorch=1.2.0
  - scikit-image=0.16.2
  - scipy=1.3.2
  - seaborn=0.9.0
  - torchvision=0.4.0
  - tqdm=4.36.1
  - pip:
    - sacred==0.7.5
    - scikit-learn==0.22.1
    - tensorboard
